# Generated by Django 2.1.7 on 2019-06-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotepost',
            name='dateCreation',
        ),
    ]
