# Generated by Django 2.1.7 on 2019-06-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_remove_quotepost_datecreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteauthor',
            name='lifeRange',
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
    ]
