# Generated by Django 2.1.7 on 2019-06-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64, unique=True)),
                ('famousFor', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuotePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateField()),
                ('quoteDesription', models.CharField(max_length=128)),
                ('quoteAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotesOfMan', to='basic_app.QuoteAuthor')),
            ],
        ),
    ]
